<option value="US" selected>USA
<option value="Afghanistan">Afghanistan
<option value="Albania">Albania
<option value="Algeria">Algeria
<option value="Andorra">Andorra
<option value="Angola">Angola
<option value="Antarctia">Antarctia
<option value="Antigua">Antigua
<option value="Argentina">Argentina
<option value="Armenia">Armenia
<option value="Australia">Australia
<option value="Austria">Austria
<option value="Azerbaijan">Azerbaijan
<option value="Bahamas">Bahamas
<option value="Bahrain">Bahrain
<option value="Bangladesh">Bangladesh
<option value="Barbados">Barbados
<option value="Belarus">Belarus
<option value="Belgium">Belgium
<option value="Belize">Belize
<option value="Benin">Benin
<option value="Bermuda">Bermuda
<option value="Bhutan">Bhutan
<option value="Bolivia">Bolivia
<option value="Botswana">Botswana
<option value="Brazil">Brazil
<option value="Britain">Britain
<option value="Brunei Darussalam">Brunei Darussalam
<option value="Bulgaria">Bulgaria
<option value="Burma">Burma
<option value="Burundi">Burundi
<option value="Cambodia">Cambodia
<option value="Cameroon">Cameroon
<option value="Canada">Canada
<option value="Cayman Islands">Cayman Islands
<option value="Central African Rep.">Central African Rep.
<option value="Chad">Chad
<option value="Chile">Chile
<option value="China">China
<option value="Colombia">Colombia
<option value="Congo">Congo
<option value="Costa Rica">Costa Rica
<option value="Cuba">Cuba
<option value="Cyprus">Cyprus
<option value="Czechoslovakia">Czechoslovakia
<option value="Denmark">Denmark
<option value="Dominican Republic">Dominican Republic
<option value="Ecuador">Ecuador
<option value="Egypt">Egypt
<option value="El Salvador">El Salvador
<option value="England">England
<option value="Equatorial Guinea">Equatorial Guinea
<option value="Estonia">Estonia
<option value="Ethiopia">Ethiopia
<option value="Falkland Islands">Falkland Islands
<option value="Finland">Finland
<option value="France">France
<option value="French West Indies">French West Indies
<option value="Gabon">Gabon
<option value="Gambia">Gambia
<option value="Georgia">Georgia
<option value="Germany">Germany
<option value="Ghana">Ghana
<option value="Gibraltar">Gibraltar
<option value="Great Britain">Great Britain
<option value="Greece">Greece
<option value="Greenland">Greenland
<option value="Grenada">Grenada
<option value="Guadeloupe">Guadeloupe
<option value="Guam">Guam
<option value="Guatemala">Guatemala
<option value="Guinea">Guinea
<option value="Guyana">Guyana
<option value="Haiti">Haiti
<option value="Honduras">Honduras
<option value="Hong Kong">Hong Kong
<option value="Hungary">Hungary
<option value="Iceland">Iceland
<option value="India">India
<option value="Indonesia">Indonesia
<option value="Iran">Iran
<option value="Iraq">Iraq
<option value="Iraq-Saudi Arabia Neutra">Iraq-Saudi Arabia Neutra
<option value="Ireland">Ireland
<option value="Israel">Israel
<option value="Italy">Italy
<option value="Ivory Coast">Ivory Coast
<option value="Jamaica">Jamaica
<option value="Japan">Japan
<option value="Jordan">Jordan
<option value="Kazakhstan">Kazakhstan
<option value="Kenya">Kenya
<option value="Kuwait">Kuwait
<option value="Kyrgyzstan">Kyrgyzstan
<option value="Laos">Laos
<option value="Latvia">Latvia
<option value="Lebanon">Lebanon
<option value="Lesotho">Lesotho
<option value="Liberia">Liberia
<option value="Libya">Libya
<option value="Liechtenstein">Liechtenstein
<option value="Lithuania">Lithuania
<option value="Luxembourg">Luxembourg
<option value="Macau">Macau
<option value="Madagascar">Madagascar
<option value="Malaysia">Malaysia
<option value="Mali">Mali
<option value="Malta">Malta
<option value="Mauritania">Mauritania
<option value="Mauritius">Mauritius
<option value="Mexico">Mexico
<option value="Moldova">Moldova
<option value="Monaco">Monaco
<option value="Morocco">Morocco
<option value="Mozambique">Mozambique
<option value="Namibia">Namibia
<option value="Nepal">Nepal
<option value="Netherlands">Netherlands
<option value="Netherlands Antilles">Netherlands Antilles
<option value="New Zealand">New Zealand
<option value="Nicaragua">Nicaragua
<option value="Niger">Niger
<option value="Nigeria">Nigeria
<option value="North Korea">North Korea
<option value="Northern Ireland">Northern Ireland
<option value="Norway">Norway
<option value="Oman">Oman
<option value="Pakistan">Pakistan
<option value="Palau">Palau
<option value="Panama">Panama
<option value="Papua New Guinea">Papua New Guinea
<option value="Paraguay">Paraguay
<option value="Peru">Peru
<option value="Philippines">Philippines
<option value="Poland">Poland
<option value="Portugal">Portugal
<option value="Qatar">Qatar
<option value="Romania">Romania
<option value="Russia">Russia
<option value="Rwanda">Rwanda
<option value="Saint Helena">Saint Helena
<option value="Saint Vincent">Saint Vincent
<option value="San Marino">San Marino
<option value="Saudi Arabia">Saudi Arabia
<option value="Senegal">Senegal
<option value="Sierra Leone">Sierra Leone
<option value="Singapore">Singapore
<option value="Somalia">Somalia
<option value="South Africa">South Africa
<option value="South Korea">South Korea
<option value="Spain">Spain
<option value="Sri Lanka">Sri Lanka
<option value="Sudan">Sudan
<option value="Suriname">Suriname
<option value="Swaziland">Swaziland
<option value="Sweden">Sweden
<option value="Switzerland">Switzerland
<option value="Syria">Syria
<option value="Tahiti">Tahiti
<option value="Taiwan">Taiwan
<option value="Tajikistan">Tajikistan
<option value="Tanzania">Tanzania
<option value="Thailand">Thailand
<option value="Togo">Togo
<option value="Trinidad West Indies">Trinidad West Indies
<option value="Tunisia">Tunisia
<option value="Turkey">Turkey
<option value="Turkmenistan">Turkmenistan
<option value="Uganda">Uganda
<option value="Ukraine">Ukraine
<option value="United Arab Emirates">United Arab Emirates
<option value="United Kingdom">United Kingdom
<option value="Uruguay">Uruguay
<option value="Uzbekistan">Uzbekistan
<option value="Venezuela">Venezuela
<option value="Vietnam">Vietnam
<option value="Virgin Islands">Virgin Islands
<option value="Wales">Wales
<option value="Yemen">Yemen
<option value="Yugoslavia">Yugoslavia
<option value="Zambia">Zambia
<option value="Zimbabwe">Zimbabwe



